[package]
name = 'manifoldsr'
publish = false
version = '0.1.0'
edition = '2021'
rust-version = '1.85'

[lib]
crate-type = ['staticlib']
name = 'manifoldsr'

[dependencies]
bixverse-rs = "0.1.1"
extendr-api = '0.8.1'
faer = "0.23.2"
faer-entity = "0.20.1"

[target.'cfg(not(windows))'.dependencies]
manifolds-rs = { version = "0.1.8", features = [
    "fft_tsne",
] }

[target.'cfg(windows)'.dependencies]
manifolds-rs = { version = "0.1.8" }

[profile.test]
opt-level = 3
debug = false

[profile.release]
opt-level = 3
lto = "thin"
codegen-units = 1

[lints.rust]
non_snake_case = "allow"
