# Generated by extendr: Do not edit by hand
# nolint start

#' @usage NULL
#' @useDynLib manifoldsR, .registration = TRUE
NULL

#' UMAP implementation
#'
#' @description
#' `r lifecycle::badge("experimental")`
#' Leverages the UMAP implementation in manifolds-rs - a very fast Rust-based
#' implementation.
#'
#' @param embd Numerical matrix. The data to use to generate the embeddings.
#' Should be of dimensions samples x features.
#' @param n_dim Integer. Number of UMAP dimensions to return.
#' @param min_dist Numeric. Minimum distance to use.
#' @param spread Numeric. Spread parameter to use.
#' @param k Integer. Number of nearest neighbours to consider
#' @param umap_params Named list. List that contains all of the key parameters
#' for the UMAP generation.
#' @param seed Integer. Seed for reproducibility.
#' @param use_high_precision Optional logical. Controls `fp32` vs `fp64` for.
#' If `NULL` will use sensible default thresholding.
#' @param verbose Integer. If `0L` -> silent or `1L` for normal verbosity; `2L`
#' for detailed verbosity.
#'
#' @return The UMAP embeddings.
#'
#' @export
rs_umap <- function(embd, n_dim, min_dist, spread, k, umap_params, seed, use_high_precision, verbose) .Call(wrap__rs_umap, embd, n_dim, min_dist, spread, k, umap_params, seed, use_high_precision, verbose)

#' UMAP implementation
#'
#' @description
#' `r lifecycle::badge("experimental")`
#' Leverages the UMAP implementation in manifolds-rs - a very fast Rust-based
#' implementation. This version uses a pre-computed kNN graph, please see
#' [new_nearest_neighbour()].
#'
#' @param embd Numerical matrix. The data to use to generate the embeddings.
#' Should be of dimensions samples x features.
#' @param knn_data `NearestNeighbours` class from R.
#' @param n_dim Integer. Number of UMAP dimensions to return.
#' @param min_dist Numeric. Minimum distance to use.
#' @param spread Numeric. Spread parameter to use.
#' @param k Integer. Number of nearest neighbours to consider
#' @param umap_params Named list. List that contains all of the key parameters
#' for the UMAP generation.
#' @param seed Integer. Seed for reproducibility.
#' @param use_high_precision Optional logical. Controls `fp32` vs `fp64` for.
#' If `NULL` will use sensible default thresholding.
#' @param verbose Integer. If `0L` -> silent or `1L` for normal verbosity; `2L`
#' for detailed verbosity.
#'
#' @return The UMAP embeddings.
#'
#' @export
rs_umap_from_knn <- function(embd, knn_data, n_dim, min_dist, spread, k, umap_params, seed, use_high_precision, verbose) .Call(wrap__rs_umap_from_knn, embd, knn_data, n_dim, min_dist, spread, k, umap_params, seed, use_high_precision, verbose)

#' tSNE implementation
#'
#' @description
#' `r lifecycle::badge("experimental")`
#' Leverages the tSNE implementation in manifolds-rs - a very fast Rust-based
#' implementation. You have two optimiser options: `"bh"` which tends to be
#' faster on smaller datasets and `"fft"` for large data sets.
#'
#' @param embd Numerical matrix. The data to use to generate the embeddings.
#' Should be of dimensions samples x features.
#' @param n_dim Integer. Number of tSNE dimensions to return. Needs to be two,
#' others are not supported.
#' @param perplexity Numeric. The tSNE perplexity parameter.
#' @param approx_type String. One of `c("fft", "bh")`. Which of the two
#' approximations to use.
#' @param tsne_params Named list. List that contains all of the key parameters
#' for the tSNE generation.
#' @param seed Integer. Seed for reproducibility.
#' @param use_high_precision Optional logical. Controls `fp32` vs `fp64` for.
#' If `NULL` will use sensible default thresholding.
#' @param verbose Integer. If `0L` -> silent or `1L` for normal verbosity; `2L`
#' for detailed verbosity.
#'
#' @return The tSNE embeddings.
#'
#' @export
rs_tsne <- function(embd, n_dim, perplexity, approx_type, tsne_params, seed, use_high_precision, verbose) .Call(wrap__rs_tsne, embd, n_dim, perplexity, approx_type, tsne_params, seed, use_high_precision, verbose)

#' tSNE implementation
#'
#' @description
#' `r lifecycle::badge("experimental")`
#' Leverages the tSNE implementation in manifolds-rs - a very fast Rust-based
#' implementation. You have two optimiser options: `"bh"` which tends to be
#' faster on smaller datasets and `"fft"` for large data sets. This version
#' uses a pre-computed kNN graph, please see [new_nearest_neighbour()].
#'
#' @param embd Numerical matrix. The data to use to generate the embeddings.
#' Should be of dimensions samples x features.
#' @param knn_data `NearestNeighbours` class from R.
#' @param n_dim Integer. Number of tSNE dimensions to return. Needs to be two,
#' others are not supported.
#' @param perplexity Numeric. The tSNE perplexity parameter.
#' @param approx_type String. One of `c("fft", "bh")`. Which of the two
#' approximations to use.
#' @param tsne_params Named list. List that contains all of the key parameters
#' for the tSNE generation.
#' @param seed Integer. Seed for reproducibility.
#' @param use_high_precision Optional logical. Controls `fp32` vs `fp64` for.
#' If `NULL` will use sensible default thresholding.
#' @param verbose Integer. If `0L` -> silent or `1L` for normal verbosity; `2L`
#' for detailed verbosity.
#'
#' @return The tSNE embeddings.
#'
#' @export
rs_tsne_from_knn <- function(embd, knn_data, n_dim, perplexity, approx_type, tsne_params, seed, use_high_precision, verbose) .Call(wrap__rs_tsne_from_knn, embd, knn_data, n_dim, perplexity, approx_type, tsne_params, seed, use_high_precision, verbose)

#' Run PHATE dimensionality reduction
#'
#' @description
#' `r lifecycle::badge("experimental")`
#' Leverages the PHATE implementation in manifolds-rs - a very fast Rust-based
#' implementation.
#'
#' @param embd Numerical matrix. The data to embed of shape samples x
#' features.
#' @param n_dim Integer. Number of PHATE dimensions to return. Currently only
#' `2L` is supported.
#' @param k Integer. Number of nearest neighbours for graph construction.
#' @param phate_params Named list. Contains all key parameters for PHATE,
#' see [params_phate()] and [params_nn()].
#' @param seed Integer. Seed for reproducibility.
#' @param use_high_precision Optional logical. Controls `fp32` vs `fp64` for.
#' If `NULL` will use sensible default thresholding.
#' @param verbose Integer. If `0L` -> silent or `1L` for normal verbosity; `2L`
#' for detailed verbosity.
#'
#' @return The PHATE embedding as a matrix of shape samples x n_dim.
#'
#' @export
rs_phate <- function(embd, n_dim, k, phate_params, seed, use_high_precision, verbose) .Call(wrap__rs_phate, embd, n_dim, k, phate_params, seed, use_high_precision, verbose)

#' Run PHATE dimensionality reduction from a precomputed kNN graph
#'
#' @description
#' `r lifecycle::badge("experimental")`
#' Leverages the PHATE implementation in manifolds-rs - a very fast Rust-based
#' implementation. This version uses a pre-computed kNN graph, please see
#' [new_nearest_neighbour()].
#'
#' @param embd Numerical matrix. The data to embed of shape samples x
#' features.
#' @param knn_data `NearestNeighbours` class from R.
#' @param n_dim Integer. Number of PHATE dimensions to return. Currently only
#' `2L` is supported.
#' @param k Integer. Number of nearest neighbours used during graph
#' construction. Must match the k used to generate `knn_data`.
#' @param phate_params Named list. Contains all key parameters for PHATE,
#' see [params_phate()] and [params_nn()].
#' @param seed Integer. Seed for reproducibility.
#' @param use_high_precision Optional logical. Controls `fp32` vs `fp64` for.
#' If `NULL` will use sensible default thresholding.
#' @param verbose Integer. If `0L` -> silent or `1L` for normal verbosity; `2L`
#' for detailed verbosity.
#'
#' @return The PHATE embedding as a matrix of shape samples x n_dim.
#'
#' @export
rs_phate_from_knn <- function(embd, knn_data, n_dim, k, phate_params, seed, use_high_precision, verbose) .Call(wrap__rs_phate_from_knn, embd, knn_data, n_dim, k, phate_params, seed, use_high_precision, verbose)

#' PaCMAP implementation
#'
#' @description
#' `r lifecycle::badge("experimental")`
#' Leverages the PacMAP implementation in manifolds-rs - a very fast Rust-based
#' implementation.
#'
#' @param embd Numerical matrix. The data to use to generate the embeddings.
#' Should be of dimensions samples x features.
#' @param n_dim Integer. Number of dimensions to return.
#' @param pacmap_params Named list. List that contains all of the key
#' parameters for the PaCMAP generation.
#' @param seed Integer. Seed for reproducibility.
#' @param use_high_precision Optional logical. Controls `fp32` vs `fp64` for.
#' If `NULL` will use sensible default thresholding.
#' @param verbose Integer. If `0L` -> silent or `1L` for normal verbosity; `2L`
#' for detailed verbosity.
#'
#' @return The PaCMAP embeddings.
#'
#' @export
rs_pacmap <- function(embd, n_dim, pacmap_params, seed, use_high_precision, verbose) .Call(wrap__rs_pacmap, embd, n_dim, pacmap_params, seed, use_high_precision, verbose)

#' PaCMAP implementation with pre-computed kNN
#'
#' @description
#' `r lifecycle::badge("experimental")`
#' Leverages the PacMAP implementation in manifolds-rs - a very fast Rust-based
#' implementation. This version uses a pre-computed kNN graph, please see
#' [new_nearest_neighbour()].
#'
#' @param embd Numerical matrix. The data to use to generate the embeddings.
#' Should be of dimensions samples x features.
#' @param knn_data `NearestNeighbours` class from R.
#' @param n_dim Integer. Number of dimensions to return.
#' @param pacmap_params Named list. List that contains all of the key
#' parameters for the PaCMAP generation.
#' @param seed Integer. Seed for reproducibility.
#' @param use_high_precision Optional logical. Controls `fp32` vs `fp64` for.
#' If `NULL` will use sensible default thresholding.
#' @param verbose Integer. If `0L` -> silent or `1L` for normal verbosity; `2L`
#' for detailed verbosity.
#'
#' @return The PaCMAP embeddings.
#'
#' @export
rs_pacmap_from_knn <- function(embd, knn_data, n_dim, pacmap_params, seed, use_high_precision, verbose) .Call(wrap__rs_pacmap_from_knn, embd, knn_data, n_dim, pacmap_params, seed, use_high_precision, verbose)

#' Diffusion maps implementation
#'
#' @description
#' `r lifecycle::badge("experimental")`
#' Leverages the Diffusion Maps implementation in manifolds-rs - a very fast
#' Rust-based implementation.
#'
#' @param embd Numerical matrix. The data to use to generate the embeddings.
#' Should be of dimensions samples x features.
#' @param n_dim Integer. Number of dimensions to return.
#' @param k Integer. Number of nearest neighbours to consider.
#' @param dm_params Named list. List that contains all of the key parameters
#' for the diffusion maps generation.
#' @param seed Integer. Seed for reproducibility.
#' @param use_high_precision Optional logical. Controls `fp32` vs `fp64` for.
#' If `NULL` will use sensible default thresholding.
#' @param verbose Integer. If `0L` -> silent or `1L` for normal verbosity; `2L`
#' for detailed verbosity.
#'
#' @return The diffusion maps embeddings.
#'
#' @export
rs_diffusion_maps <- function(embd, n_dim, k, dm_params, seed, use_high_precision, verbose) .Call(wrap__rs_diffusion_maps, embd, n_dim, k, dm_params, seed, use_high_precision, verbose)

#' Diffusion maps implementation with pre-computed kNN
#'
#' @description
#' `r lifecycle::badge("experimental")`
#' Leverages the Diffusion Maps implementation in manifolds-rs - a very fast
#' Rust-based implementation. This version uses a pre-computed kNN graph, please see
#' [new_nearest_neighbour()].
#'
#' @param embd Numerical matrix. The data to use to generate the embeddings.
#' Should be of dimensions samples x features.
#' @param knn_data `NearestNeighbours` class from R.
#' @param n_dim Integer. Number of dimensions to return.
#' @param k Integer. Number of nearest neighbours to consider.
#' @param dm_params Named list. List that contains all of the key parameters
#' for the diffusion maps generation.
#' @param seed Integer. Seed for reproducibility.
#' @param use_high_precision Optional logical. Controls `fp32` vs `fp64` for.
#' If `NULL` will use sensible default thresholding.
#' @param verbose Integer. If `0L` -> silent or `1L` for normal verbosity; `2L`
#' for detailed verbosity.
#'
#' @return The diffusion maps embeddings.
#'
#' @export
rs_diffusion_maps_from_knn <- function(embd, knn_data, n_dim, k, dm_params, seed, use_high_precision, verbose) .Call(wrap__rs_diffusion_maps_from_knn, embd, knn_data, n_dim, k, dm_params, seed, use_high_precision, verbose)

#' EVoC clustering
#'
#' @description
#' `r lifecycle::badge("experimental")`
#' Wrapper function into the Rust interface for EVoC clustering.
#'
#' @param embd Numerical matrix. The data to cluster. Should be of dimensions
#' samples x features.
#' @param n_neighbours Integer. Number of nearest neighbours for graph
#' construction.
#' @param evoc_params Named list. List that contains all of the key parameters
#' for EVoC clustering.
#' @param return_knn Boolean. Shall the kNN graph be returned.
#' @param seed Integer. Seed for reproducibility.
#' @param use_high_precision Optional logical. Controls `fp32` vs `fp64` for.
#' If `NULL` will use sensible default thresholding.
#' @param verbose Integer. If `0L` -> silent or `1L` for normal verbosity; `2L`
#' for detailed verbosity.
#'
#' @return A named list with:
#' \itemize{
#'   \item evoc_res - List with the EVoC results
#'   \item knn - Optional list (can be NULL) with the kNN graph
#' }
#'
#' @export
rs_evoc <- function(embd, n_neighbours, evoc_params, return_knn, seed, use_high_precision, verbose) .Call(wrap__rs_evoc, embd, n_neighbours, evoc_params, return_knn, seed, use_high_precision, verbose)

#' EVoC clustering from pre-computed kNN
#'
#' @description
#' `r lifecycle::badge("experimental")`
#' Wrapper function into the Rust interface for EVoC clustering. This version
#' uses a pre-computed kNN graph, please see [new_nearest_neighbour()].
#'
#' @param embd Numerical matrix. The data to cluster. Should be of dimensions
#' samples x features.
#' @param knn_data List. A NearestNeighbours object with `k`, `indices`, and
#' `dist` elements.
#' @param n_neighbours Integer. Number of nearest neighbours for graph
#' construction.
#' @param evoc_params Named list. List that contains all of the key parameters
#' for EVoC clustering.
#' @param seed Integer. Seed for reproducibility.
#' @param use_high_precision Optional logical. Controls `fp32` vs `fp64` for.
#' If `NULL` will use sensible default thresholding.
#' @param verbose Integer. If `0L` -> silent or `1L` for normal verbosity; `2L`
#' for detailed verbosity.
#'
#' @return A named list with cluster layers, membership strengths, persistence
#' scores, and the kNN graph.
#'
#' @export
rs_evoc_from_knn <- function(embd, knn_data, n_neighbours, evoc_params, seed, use_high_precision, verbose) .Call(wrap__rs_evoc_from_knn, embd, knn_data, n_neighbours, evoc_params, seed, use_high_precision, verbose)

#' K-means clustering (full)
#'
#' @description
#' `r lifecycle::badge("experimental")`
#' Rust interface for k-means clustering using Lloyd's algorithm with SIMD or
#' GEMM acceleration depending on dimensionality. It exposes the high
#' performance k-means clustering code from the Rust crate `ann-search-rs`
#' for rapid clustering.
#'
#' @param data Numerical matrix. The data to cluster, of dimensions
#' samples x features.
#' @param k Integer. Number of clusters.
#' @param kmeans_params Named list. Parameters produced by `params_kmeans()`.
#' @param seed Integer. Seed for reproducibility.
#' @param verbose Boolean. Controls verbosity.
#'
#' @return A named list with:
#' \itemize{
#'   \item centroids - Numeric matrix of shape k x features.
#'   \item assignments - Integer vector of length samples (1-indexed).
#' }
#'
#' @export
rs_k_means <- function(data, k, kmeans_params, seed, verbose) .Call(wrap__rs_k_means, data, k, kmeans_params, seed, verbose)

#' Mini-batch k-means clustering
#'
#' @description
#' `r lifecycle::badge("experimental")`
#' Rust interface for mini batch k-means clustering from `bixverse-rs`. This
#' version can be very useful in cases where you overcluster the data.
#'
#' @param data Numerical matrix. The data to cluster, of dimensions
#' samples x features.
#' @param k Integer. Number of clusters.
#' @param kmeans_params Named list. Parameters produced by `params_kmeans()`.
#' @param seed Integer. Seed for reproducibility.
#' @param verbose Boolean. Controls verbosity.
#'
#' @return A named list with:
#' \itemize{
#'   \item centroids - Numeric matrix of shape k x features.
#'   \item assignments - Integer vector of length samples (1-indexed).
#' }
#'
#' @export
rs_k_means_mini_batch <- function(data, k, kmeans_params, seed, verbose) .Call(wrap__rs_k_means_mini_batch, data, k, kmeans_params, seed, verbose)

#' Wrapper around some nearest neighbour searches integrated into manifold-rs
#'
#' @description
#' `r lifecycle::badge("experimental")`
#' This is an interface into various (approximate) nearest neighbour searches
#' implemented in the Rust crate `ann-search-rs`. They designed for incredible
#' fast in-memory searches for kNN generation.
#'
#' @param data Numeric matrix. Shape of samples x n_dim for which to get the
#' (approximate) nearest neighbours
#' @param k Integer. Number of neighbours to return
#' @param ann_method String. Which of the methods to use. One of
#' `c("hsnw", "balltree", "annoy", "nndescent")`
#' @param ann_params Named list. Contains the nearest neighbour parameters.
#' @param seed Integer. Seed for reproducibility
#' @param verbose Integer. If `0L` -> silent or `1L` for normal verbosity; `2L`
#' for detailed verbosity.
#'
#' @returns A list with the following elements
#' \itemize{
#'   \item indices - flat representation of the indices.
#'   \item dist - flat representaitons of the distances.
#'   \item k - number of neighbours.
#'   \item n - number of samples.
#' }
#'
#' @export
rs_approx_nearest_neighbours <- function(data, k, ann_method, ann_params, seed, verbose) .Call(wrap__rs_approx_nearest_neighbours, data, k, ann_method, ann_params, seed, verbose)

#' Generates the SwissRole data
#'
#' @description
#' `r lifecycle::badge("experimental")`
#' Generates synthetic data, i.e., the Swiss role to test different manifold
#' learning techniques
#'
#' @param n_samples Integer. Number of data points to generate.
#' @param noise Numeric. How much noise to add.
#' @param seed Integer. For reproducibility purposes
#'
#' @return The swiss role synthetic data with the desired parameters.
#'
#' @export
rs_data_swiss_role <- function(n_samples, noise, seed) .Call(wrap__rs_data_swiss_role, n_samples, noise, seed)

#' Generates the SwissRole data
#'
#' @description
#' `r lifecycle::badge("experimental")`
#' Generates synthetic data, i.e., the Swiss role to test different manifold
#' learning techniques
#'
#' @param n_samples Integer. Number of data points to generate.
#' @param noise Numeric. How much noise to add.
#' @param bias Numeric. Sampling bias along `t`. `0.0` recovers uniform
#' sampling; higher values concentrate samples at the inner end of the roll. A
#' value of `2.5` mirrors the trajectory accumulation behaviour.
#' @param seed Integer. For reproducibility purposes
#'
#' @return The biased swiss role synthetic data with the desired parameters.
#'
#' @export
rs_data_biased_swiss_role <- function(n_samples, noise, bias, seed) .Call(wrap__rs_data_biased_swiss_role, n_samples, noise, bias, seed)

#' Generates clustered data
#'
#' @description
#' `r lifecycle::badge("experimental")`
#' Generates synthetic data with clear cluster structure.
#'
#' @param n_samples Integer. Number of data points to generate.
#' @param dim Integer. Dimensionality of the data
#' @param n_clusters Integer. Number of clusters to produce in the data.
#' @param seed Integer. For reproducibility purposes
#'
#' @return A list with the following elements:
#' \itemize{
#'  \item data - Numerical matrix with the data.
#'  \item clusters - Cluster assignments
#' }
#'
#' @export
rs_data_clusters <- function(n_samples, dim, n_clusters, seed) .Call(wrap__rs_data_clusters, n_samples, dim, n_clusters, seed)

#' Generates tree-like data with branches
#'
#' @description
#' `r lifecycle::badge("experimental")`
#' Generates synthetic data that has a tree-like structure to simulate
#' evolution/trajectory of data.
#'
#' @param n_samples Integer. Number of data points to generate.
#' @param dim Integer. Dimensionality of the data.
#' @param topology String. One of `c("bifurcation", "linear", "combination")`.
#' @param cell_trajectories List or NULL. Named list with three equal-length
#'   vectors: `parent` (integer, NA for root, zero-indexed), `split_at`
#'   (numeric, fraction along parent where branch starts), and `length`
#'   (numeric, length of the branch). If NULL, will use the topology specified
#'   in topology.
#' @param noise Numeric. How much noise to add.
#' @param seed Integer. For reproducibility purposes.
#'
#' @return A list with the following elements:
#' \itemize{
#'  \item data - Numerical matrix with the generated data.
#'  \item branches - Branch assignments for each sample.
#' }
#'
#' @export
rs_data_trajectory <- function(n_samples, dim, topology, cell_trajectories, noise, seed) .Call(wrap__rs_data_trajectory, n_samples, dim, topology, cell_trajectories, noise, seed)

#' Generate hierarchical cluster data
#'
#' @description
#' `r lifecycle::badge("experimental")`
#' Generates synthetic data with a two-level cluster hierarchy: `n_supergroups`
#' top-level groups each containing `n_subclusts` tight subclusters. Supergroup
#' centres are spread far apart; subcluster centres sit tightly around their
#' supergroup centre.
#'
#' Note that the actual number of samples returned may be slightly less than
#' `n_samples` if it is not evenly divisible by `n_supergroups * n_subclusts`.
#'
#' @param n_samples Integer. Total number of points, distributed evenly across
#' all subclusters.
#' @param dim Integer. Dimensionality of the ambient space.
#' @param n_supergroups Integer. Number of top-level groups. Defaults to `3`.
#' @param n_subclusts Integer. Number of subclusters per supergroup. Defaults
#' to `3`.
#' @param supergroup_spread Numeric. Spread of supergroup centres. Defaults to
#' `15.0`.
#' @param subcluster_spread Numeric. Spread of subcluster centres around their
#' supergroup centre. Defaults to `2.0`.
#' @param point_std Numeric. Within-subcluster Gaussian noise. Defaults to
#' `0.4`.
#' @param seed Integer. Seed for reproducibility.
#'
#' @return A named list with three elements: `data`, a numeric matrix of shape
#' samples x `dim`; `supergroup`, an integer vector of supergroup labels
#' (`0..n_supergroups`) one per sample; and `subgroup`, an integer vector of
#' subcluster labels (`0..n_supergroups * n_subclusts`) one per sample.
#'
#' @export
rs_data_hierarchical <- function(n_samples, dim, n_supergroups, n_subclusts, supergroup_spread, subcluster_spread, point_std, seed) .Call(wrap__rs_data_hierarchical, n_samples, dim, n_supergroups, n_subclusts, supergroup_spread, subcluster_spread, point_std, seed)

#' Check cluster separation in an embedding
#'
#' @param embd Numerical matrix. The embedding of shape samples x dims.
#' @param cluster_membership Integer vector. Zero-indexed cluster labels.
#'
#' @return A named list with `within_dists` and `between_dists`.
#'
#' @export
#'
#' @keywords internal
rs_check_cluster_separation <- function(embd, cluster_membership) .Call(wrap__rs_check_cluster_separation, embd, cluster_membership)

#' Adjusted Rand index
#'
#' @description
#' `r lifecycle::badge("experimental")`
#' Calculates the adjusted Rand index in Rust between two membership vectors.
#'
#' @param cluster_membership_a Integers. Cluster memberships in group a.
#' @param cluster_membership_b Integers. Cluster memberships in group b.
#'
#' @returns Returns the adjusted Rand index between the two groups.
#'
#' @export
rs_ari <- function(cluster_membership_a, cluster_membership_b) .Call(wrap__rs_ari, cluster_membership_a, cluster_membership_b)

#' Calculates the cluster silhouette scores
#'
#' @description
#' `r lifecycle::badge("experimental")`
#' Calculates the Silhouette in Rust given the original data and a membership
#' vector. Uses squared Euclidean distance under the hood for speed.
#'
#' @param data Numeric matrix. The data in shape of sample x features.
#' @param cluster_membership Integers. Cluster memberships as integers.
#'
#' @returns A list with the following items
#' \itemize{
#'  \item mean_silhouette - Mean silhouette scores per cluster.
#'  \item silhouette_scores - Silhouette scores per given data point.
#' }
#'
#' @export
rs_silhouette_score <- function(data, cluster_membership) .Call(wrap__rs_silhouette_score, data, cluster_membership)

#' Calculates the intertia for k-means clustering
#'
#' @description
#' `r lifecycle::badge("experimental")`
#' Calculates inertia for k-means clustering given the data, centroids and
#' membership
#'
#' @param data Numeric matrix. The data in shape of sample x features.
#' @param centroids Numeric matrix. The centroid data in shape k x features.
#' @param cluster_membership Integers. Cluster memberships as integers.
#'
#' @returns The inertia score
#'
#' @export
rs_intertia <- function(data, centroids, cluster_membership) .Call(wrap__rs_intertia, data, centroids, cluster_membership)

# nolint end
